### PR TITLE
chore(cla): add my details to the csv

### PR DESCRIPTION
**Pull request by drahnr**
As requested, in https://github.com/ockam-network/ockam/pull/809#issuecomment-772975536

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
@drahnr Thank you. Could you rebase this to main.

**Comment by drahnr** [comment]
Err, silly gh ui does not play well and only does merges.

**Comment by drahnr** [comment]
Ready again

**Review by mrinalwadhwa — APPROVED** [review]

**Review by mrinalwadhwa — CHANGES_REQUESTED** [review]
Thank you.
The commit isn't signed, could you sign it please.

**Comment by drahnr** [comment]
Signed :)

**Comment by mrinalwadhwa** [comment]
Maybe you forgot to push the new commit, the current one doesn't looks like it's signed.
Github has a guide for this here, it may be helpful in diagnosing the problem
https://docs.github.com/en/github/authenticating-to-github/signing-commits


Screen Shot 2021-02-10 at 7 38 40 AM

Screen Shot 2021-02-10 at 7 38 05 AM

**Comment by drahnr** [comment]
I can verify it locally, which equiv to what I did earlier today.

```
# git verify-commit HEAD
gpg: Signature made Mi 10 Feb 2021 19:58:22 CET
gpg:                using RSA key ABD136FC12D4991BF0260298EF08D41352004815
gpg: Good signature from "Bernhard Schuster <bernhard@ahoi.io>" [<snip>]
```

**Review by mrinalwadhwa — APPROVED** [review]

**Comment by mrinalwadhwa** [comment]
Thank you 🙏  Merged.

**Pull request merged**
