### PR TITLE
Added Abhijit Gadgil as contributor

### PR DESCRIPTION
**Pull request by gabhijit**

### CODE REVIEW

**Comment by mrinalwadhwa** [comment]
Thank you for sending this 🙏 
We require that all commits are GPG signed. Could you sign it please.

**Comment by gabhijit** [comment]
> Thank you for sending this pray
> We require that all commits are GPG signed. Could you sign it please.

Done!

**Review by mrinalwadhwa — APPROVED** [review]

**Comment by jared-s** [comment]
Hi @gabhijit ! Would you mind please rebasing this PR? We had a change to a file before we merged this branch, sorry about that!

**Comment by gabhijit** [comment]
@jared-s Done.

**Pull request merged**
